### PR TITLE
Prevent deno format from messing with .md files

### PR DESCRIPTION
**Pull request by DebitCardz**

### CODE REVIEW

**Comment by CoreyShupe** [comment]
Why would we want this behavior if deno fmt properly formats md files. I figure if it becomes an issue then we can deal with it. I don't think it's a big issue right now if it formats them properly. https://github.com/denoland/deno/pull/8887 It looks like they specifically deal with it properly. We might want to leave it until it becomes a real issue.

**Comment by DebitCardz** [comment]
> Why would we want this behavior if deno fmt properly formats md files. I figure if it becomes an issue then we can deal with it. I don't think it's a big issue right now if it formats them properly. [denoland/deno#8887](https://github.com/denoland/deno/pull/8887) It looks like they specifically deal with it properly. We might want to leave it until it becomes a real issue.

I didn't exactly know how they formatted md files and while looking at the docs I saw you could do that so I thought why not, not a needed change we can ignore this for now.

**Comment by CoreyShupe** [comment]
I'm going to close this PR in favor of letting deno format MD files, if it becomes an issue in the future even past the suggested PR we can submit an issue for the issue and add the ignore file. Going to deny this as is.

**Comment by CoreyShupe** [comment]
Re-opening due to md files being formatted awkwardly in some cases.

**Pull request merged**
